falshcards:
    resource: "@FalshcardsBundle/Resources/config/routing.yml"
    prefix:   /falshcards

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
